# Generated by Django 2.2.5 on 2019-10-15 09:35

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserExtendManager()),
            ],
        ),
    ]
